#include <gtest/gtest.h>
#include <nlohmann/json.hpp>
#include <string>

namespace progressive { namespace test {
using json = nlohmann::json;
TEST(AlmostDone,T1){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_0_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T2){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_1_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T3){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_2_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T4){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_3_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T5){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_4_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T6){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_5_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T7){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_6_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T8){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_7_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T9){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_8_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T10){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_9_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T11){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_10_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T12){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_11_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T13){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_12_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T14){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_13_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T15){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_14_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T16){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_15_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T17){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_16_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T18){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_17_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T19){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_18_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T20){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_19_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T21){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_20_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T22){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_21_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T23){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_22_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T24){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_23_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T25){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_24_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T26){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_25_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T27){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_26_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T28){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_27_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T29){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_28_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T30){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_29_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T31){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_30_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T32){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_31_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T33){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_32_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T34){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_33_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T35){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_34_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T36){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_35_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T37){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_36_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T38){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_37_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T39){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_38_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T40){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_39_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T41){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_40_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T42){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_41_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T43){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_42_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T44){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_43_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}
TEST(AlmostDone,T45){json t;for(int e=0;e<3;++e){json v;v["eid"]="$ad49_44_"+std::to_string(e)+":m";v["c"]["b"]="AD"+std::to_string(e);t["evs"].push_back(v);ASSERT_FALSE(v["eid"].empty());}ASSERT_EQ(t["evs"].size(),3);auto d=t.dump();ASSERT_FALSE(d.empty());}

}}
